### ISSUE TITLE
Not Launching

### ISSUE THREAD

**Issue by y4my4my4m** [obecebo/erythros#1]
Hi, I've tried launching it with many different combination to no luck (VirtualBox, VMWare, QEMU, all not working).

![TempleOS-Erythros](https://user-images.githubusercontent.com/8145020/63136911-20de6900-c00f-11e9-9366-511c2d251641.png)

```
Intel HD Audio
VMware SVGA II graphics adapter
Virtio-net
```

Have been set, although I am unsure if I need something supplementary for virtio, I'm using libvirt on `Manjaro 4.19`. VirtualBox is `6.0.10`

Cheers.

**Comment by obecebo** [comment]
That `MultCore` exception is due to the network services being manually assigned to core #6 in testing. The VM in your screenshot only has cores #0-5 available. I had planned on fixing this for the Release later this month, but it should be fixed now as of the latest commit.

**Comment by y4my4my4m** [comment]
It didn't work without the 6th core, but that did solve the issue. 

Thanks for the prompt update.
I hope I can contribute to this project :)
