### ISSUE TITLE
Forever loading cursor animation

### ISSUE THREAD

**Issue by y4my4my4m** [obecebo/erythros#2]
I've successfully booted, the screen properly resize and everything seems ok on that front.

However the menu is not responding, the cursor can move but it is stuck in "loading". I can drag and drop to see the selection box, but that's about it.

![erythros](https://user-images.githubusercontent.com/8145020/63165998-0a183080-c068-11e9-91d2-d01c1016a47a.png)

One thing I should mention is that I'm unable to run 
`Cd("T:/"); #include "Run";` as a single command, it says `C:/Home/Run.HC` not found.
Running simply the include after going into T: works though, but perhaps some files are trying to be accessed from C: somehow?

I've tried `CopyTree("T:/","C:/");` but it would crash once it gets to icons/16 because of the amount of files. (CopyTree actually takes the entire tree and all it's files in memory, if i remember correctly).

**Comment by obecebo** [comment]
The error with `C:/Home/Run.HC` appears to be searching the wrong location. I updated the README with the correct command for booting the environment from Adam task. Some startup tasks are still hard-coded to use the cdrom, this will be changed in the initial Release when `EOS_INSTALL_DRV` is set during installation.

I added a pre-alpha testing release that you can try [here](https://github.com/obecebo/erythros/releases/tag/v0.1.0-pre-alpha). Once the System Monitor is loaded, you can use `Launch Debugger` and execute `ShowLastTaskDoc;` to view any errors and warnings during program startup (spinning/wait cursor, unexpected behavior) until I add an error handler to GUI in WindowManager.

**Comment by y4my4my4m** [comment]
Worked like a charm. I've added it to my C drive `MakeOS.HC` and now I can launch it on boot :)

There seems to be something wrong with the inputs, though, as if you needed to press while in the correct clock cycle or something. Clicking or typing something works 1/6th of the time, but it doesn't appear to be slow or unresponsive.

![image](https://user-images.githubusercontent.com/8145020/63180640-ac94db80-c089-11e9-81c2-ed6ae6a9cf87.png)

I'll keep investigating but not sure if this is supposed to be happening in the OS's current state.

**Comment by obecebo** [comment]
There was a hard-coded value in `VBoxGuest.HC` for `KbdMsUpdateTask` to Spawn on core #5, which presumably would conflict with the network services tasks on your VM, causing choppy/unresponsive input. Latest commit should fix it, and I updated the ISO.C in the pre-release.

**Comment by y4my4my4m** [comment]
Not sure the release file properly updated but I recreated the ISO from the git and it works now :)
